docs/webhooks/01-v3-Overview.md
- Add incident_key and created_at fields to `incident` data type and `incident.priority_updated` examples
- DEVI 900 and DEVI 901
=> Add incident_key and created_at fields

docs/events-API-v1/02-Trigger-Events.md
- Fixes a typo in the Events V1 trigger events docs
=> Fix typo in Events V1 trigger events doc

docs/webhooks/01-v3-Overview.md
Add documentation for custom headers on v3 webhooks.
-[DEVI-711](https://pagerduty.atlassian.net/browse/DEVI-711)
=> DEVI-711 Add custom_headers to the delivery methods on V3 webhook_subscriptions

docs/app-integration-development/09-OAuth-2-Auth-Code-Grant.md, docs/app-integration-development/10-OAuth-2-PKCE.md
Update parts of our OAuth documentation to reflect newer requirements previously communicated.
- `scope` is now a required field. Currently, a default scope is assumed, however, this will be deprecated after May 31st, 2022
- Fix an issue where table column values were not properly assigned
=> [AF-577] Update OAuth documentation with newer requirements

docs/tool-libraries/02-API-Tools-and-Code-Samples.md
- I'd like to add PagerDuty CLI to the list of Tools and Code Samples
- No Jira ticket
=> Add PagerDuty CLI to the list of Tools and Samples

docs/webhooks/03-Mutual-TLS.md
- In the [*Mutual TLS*](https://developer.pagerduty.com/docs/ZG9jOjExMDI5NTky-mutual-tls) Webhooks doc, the link to the DigiCert Global Root CA is no longer accessible via https; this PR fixes that by linking to the PEM version of the cert as hosted by DigiCert.
Current link leads here:
- [T2D2-17](https://pagerduty.atlassian.net/browse/T2D2-17)
=> fix link to root cert in webhooks doc

docs/app-integration-development/07-Writing-App-Event-Transformers.md, docs/events-API-v1/03-Custom-Event-Transformer.md
- Documenting newly imposed event transform fanout limit on PD.emitEventsV2 and PD.emitGenericEvents methods
- [Update public documentation and API contracts to note the event transform fanout limit](https://pagerduty.atlassian.net/browse/ING-930)
=> Update public documentation and API contracts to note the event transform fanout limit

docs/webhooks/02-Behavior.md, docs/webhooks/11-Webhook-IPs.md, toc.json
- Add a page with the new EIP/NAT Gateway Fixed IPs that squids will use to deliver Generic Webhooks
- requires https://github.com/PagerDuty/developer-site/pull/642
- [DEVI-859](https://pagerduty.atlassian.net/browse/DEVI-859)
=> DEVI-859 - Webhook Safelist IP changes

.buildkite/stg-pipeline.yml, docs/webhooks/11-Webhook-IPs.md
The developer docs staging build/push (and most likely prod too) is broken due to an upgrade in npm versions. We don't pin the `node:alpine` image thats used for the build/upload to stoplight.
https://pagerduty.atlassian.net/browse/DEVI-1177
=> Broken Stoplight build-push

docs/REST-API/17-Audit-Records-API.md
- The doc wrongly stated that audit records were available for 18 months. They are
available for 12 months
- EF-2920
=> [EF-2920] Update audit records doc

docs/app-integration-development/08-OAuth-2-Functionality.md, docs/app-integration-development/09-OAuth-2-Auth-Code-Grant.md, docs/app-integration-development/10-OAuth-2-PKCE.md
[AF-915](https://pagerduty.atlassian.net/browse/AF-915) 
Now that https://pagerduty.atlassian.net/browse/AF-915 is finished we can move our docs to point to `identity.pagerduty.com`.
=> [AF-915] Move things to identity dot pagerduty dot com

docs/REST-API/17-Audit-Records-API.md
I noticed that the links from the Audit Trail Developer Docs to the Audit Trail API docs appeared to be broken. I believe they just weren't updated when we switched the URL structure recently.
This PR points them to the current equivalent URLs from the previous links that were broken.
The fixed links can be viewed on [this page in staging](https://developer-v2.pd-staging.com/docs/606d11bd5bceb-audit-records-api) but please note that the links are hard-coded to the production API docs to do limitations of the docs platform [discussed here](https://pagerduty.slack.com/archives/CP897F8BC/p1658863923411069?thread_ts=1658500015.640739&cid=CP897F8BC).
No JIRA ticket for this since it's just a small side quest I noticed while investigating something else. Happy to create one if process requires …
=> Fix Audit Trail API doc links.

docs/REST-API/16-Global-Event-Rules-API.md
Fix the links to a few broken images on this page: https://developer.pagerduty.com/docs/ZG9jOjExMDI5NTY1-global-event-rules-api
New relative paths are inspired by https://github.com/PagerDuty/developer-docs/blob/d2a0b4d2ddfe4c9abbbb68d0276b6b01b508e586/docs/app-integration-development/03-Register-an-App.md?plain=1#L17 which appears correctly here: https://developer.pagerduty.com/docs/ZG9jOjExMDI5NTY5-register-an-app
I also searched the repo for other images, and all other images appear to have correct paths: https://cs.github.com/PagerDuty/developer-docs?q=%2F%5C.jpg%7C%5C.png%2F
- n/a – A quick fix in response to an internal report.
- I checked staging **but** images unrelated to this PR that appear **correctly** in production do **not** work on staging: …
=> Fix broken images on Global Event Rules API page

docs/app-integration-development/11-OAuth-2-Id-token.md
The `at_hash` is actually the hash value of the access token, not the ID token.
- AF-1157
=> [AF-1157] OpenID Connect Docs - More clear field description

docs/webhooks/08-Certificates.md
This PR updates our public certificates doc with information about the upcoming webhook certificate rotation (for `webhooks.pagerduty.com` and `webhooks.eu.pagerduty.com`), details about the new certs, and files for downloading.
The presentation of this information is also changed to a table, making it much easier to read and reference.
Related PR to upload certificate files: https://github.com/PagerDuty/developer-site/pull/801
=> [dev-docs] Add new certs for download, change format to table

docs/webhooks/08-Certificates.md
- Webhook SSL certificates for `webhooks.pagerduty.com` and `webhooks.eu.pagerduty.com` were rotated on January 6th, 2023. This PR updates the public documentation with the latest information. 
- published to staging here: https://developer-v2.pd-staging.com/docs/28fa0c4c0c883-public-certificates
https://pagerduty.atlassian.net/browse/DEVI-1417
=> update certificate info after 2023 rotation

docs/REST-API/18-PCL-Overview.md
- Noticed the changes added in https://github.com/PagerDuty/developer-docs/pull/50introduced rendered exponents wrong
This changes fixes that
https://pagerduty.atlassian.net/browse/ORCA-3847
- [x ] Check [staging environment](https://developer-v2.pd-staging.com/docs) to ensure changes look as intended.
=> ORCA-3847 fix exponent notation

docs/webhooks/01-Overview.md, docs/webhooks/20-Early-Access-Webhooks.md
Adds a new page for Early Access webhook events. The page begins with the "Early Access" warning blurb, and was not added to the toc so it doesn't appear in the sidebar. That way it's sort of "hidden" and can only be found via search or direct link.
I made the change "as simple as possible" - not trying to sort by resource type or talk about structure or what object the `data` defines (as in our public page). It just lists the events and gives an example payload. I figured this is enough to get internal developers going.
The [page on staging](https://developer-v2.pd-staging.com/docs/602d5670386dd-early-access-webhook-events).
=> Add 'hidden' docs for Early Access webhook events

docs/webhooks/01-Overview.md
- Follow up of https://github.com/PagerDuty/webhook_composition_service/pull/544, which protects V3 webhook subscriptions with scopes for Scoped OAuth requests.
- Adds scope required to subscribe to V3 webhook events
- Reformatted large list of event types into table
- [DEVI-1422 - V3 Webhook event types are protected by API Scopes](https://pagerduty.atlassian.net/browse/DEVI-1422)
=> add webhook subscription scopes and format

docs/app-integration-development/09-OAuth-2-Auth-Code-Grant.md, docs/app-integration-development/10-OAuth-2-PKCE.md
We had a recent issue where a customer was requesting an invalid scope. Currently, we still issue the access token anyways, but with only the `openid` scope. Until we improve the experience itself and deny the grant altogether, let's add in some documentation to hopefully minimize the number of people running into this.
=> Add documentation around OAuth Access Token invalid scopes requested

docs/webhooks/20-Early-Access-Webhooks.md
- Custom fields webhook payload updates
- renames `field_values` to `custom_fields`
- removes `namespace` and `multi_value`
- adds `field_type`  
https://pagerduty.atlassian.net/browse/DEVI-1614
=> DEVI-1614 - Custom fields webhook payload updates

docs/webhooks/01-Overview.md, docs/webhooks/20-Early-Access-Webhooks.md
- Moves the Incident Workflow webhooks from the EA docs to the GA docs, to be deployed in tandem with https://github.com/PagerDuty/webhook_composition_service/pull/581 .
- [DEVI-1474](https://pagerduty.atlassian.net/browse/DEVI-1474)
[DEVI-1474]: https://pagerduty.atlassian.net/browse/DEVI-1474?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
=> GA Incident Workflows events

docs/webhooks/20-Early-Access-Webhooks.md
- Added a blurb about the `incident.conference_bridge.updated` event type currently in EA, and an example payload
- [INCIDENTS-947]
[INCIDENTS-947]: https://pagerduty.atlassian.net/browse/INCIDENTS-947?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
=> [INCIDENTS-947] Add conference bridge to webhook EA documentation

docs/webhooks/01-Overview.md, docs/webhooks/20-Early-Access-Webhooks.md
- Moves the webhook documentation for custom fields and conference bridge events from EA to GA.
- [DEVI-1697](https://pagerduty.atlassian.net/browse/DEVI-1697)
[DEVI-1697]: https://pagerduty.atlassian.net/browse/DEVI-1697?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
=> Update Webhook documentation: GA custom fields and conference bridge events

docs/REST-API/19-REST-API-IPs.md
- The date at which this safelist will take effect has changed from October 25 to October 31. The changes also separate old and new IP addresses to assure the customers that the old IPs can be used until October 31.
- This PR requires https://github.com/PagerDuty/developer-site/pull/917 to be merged first
- JIRA ticket: https://pagerduty.atlassian.net/browse/SCL-2142
=> [SCL-2142] Separate old and new REST API IPs in the safelist

docs/app-integration-development/08-OAuth-Functionality.md
- it's way past October 2022 _and_ April 2023, all classic OAuth clients have the new expiry settings now ✨
=> Update obsolete OAuth expiry docs

docs/REST-API/04-Rate-Limits.md, docs/REST-API/14-Errors.md, docs/REST-API/99-Rate-Limiting-23.md, docs/events-API-v2/05-Rate-Limits.md, toc.json
- Splits the existing rate limiting documentation into separate pages for the Events API and REST API.
- Adds the initial documentation page for the upcoming changes to the REST API rate limits.
- See https://github.com/PagerDuty/captains-log/pull/1187 for the overall plan.
=> [DEVI-1762] Early access REST API ratelimit docs.

docs/REST-API/04-Rate-Limits.md
Removes "Upcoming Changes" box from Rate Limits page now that new rate limiting has been implemented.
Staging page: https://developer-v2.pd-staging.com/docs/72d3b724589e3-rest-api-rate-limits
=> remove upcoming changes

docs/webhooks/20-Early-Access-Webhooks.md
This PR updates the role assignment webhook documentation to show the changes to the `role.summary` field to show that it now allows for spaces and capital letters since it now holds `roles.description` instead of `role.name`.
- [INCIDENTS-1590](https://pagerduty.atlassian.net/browse/INCIDENTS-1590)
[INCIDENTS-1590]: https://pagerduty.atlassian.net/browse/INCIDENTS-1590?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
=> update role body to include `display_name`

docs/REST-API/06-Types.md
- Corrects the Time Zone information. The doc described the time zone identifiers as "in the format" of the IANA database. This was technically correct. However, it is also misleading. Not all values that appear in the IANA database are allowed. To clarify this a complete table of valid time zone identifiers is included. 
- EF-4783
=> [EF-4783] Correct Time Zone Description

docs/webhooks/04-Signatures.md
-  Adds some additional guidance for proper webhook signature verification.
=> Some additional notes around webhook signature verification.

docs/webhooks/03-Mutual-TLS.md
- addressing mismatch between `Mutual TLS` doc page and `Certificates` page
=> Updating cert titles and links in the MTLS page

.buildkite/stg-pipeline.yml, .github/PULL_REQUEST_TEMPLATE.md, README.md
- Update owning team for Dev Docs
- [SHAF-238](https://pagerduty.atlassian.net/browse/SHAF-238)
[SHAF-238]: https://pagerduty.atlassian.net/browse/SHAF-238?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
=> SHAF-238 - update devdocs owning Team

docs/webhooks/01-Overview.md
- Added Incident Type Update event to table
- Add Incident Type to the example
- Fix annotated event data type
- Add Incident Resolved event that was missing
[INCIDENTS-1915](https://pagerduty.atlassian.net/browse/INCIDENTS-1915)
[INCIDENTS-1915]: https://pagerduty.atlassian.net/browse/INCIDENTS-1915?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
=> Add Incident type to events and example. Plus a few other incident event fixes

docs/webhooks/01-Overview.md
- Added the new webhook event type `incident.service_update`.
- [SERVICES-2182](https://pagerduty.atlassian.net/browse/SERVICES-2182)
- https://github.com/PagerDuty/webhook_composition_service/pull/719
- https://github.com/PagerDuty/webhook_composition_service/pull/721
[SERVICES-2182]: https://pagerduty.atlassian.net/browse/SERVICES-2182?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
=> SERVICES-2182: Publish new webhook event for service reassignments

docs/REST-API/19-REST-API-IPs.md
- A few months ago, the REST API IPs page was updated to remove 2 lists of old IP addresses (one for each of the service regions). The page text still had a reference to the old and new lists, so I have removed that in this PR as it is no longer the case.
=> Remove reference to old and new IP lists on REST API lPs page

docs/webhooks/01-Overview.md
Before this change [v3 Webhook Overview docs](https://developer.pagerduty.com/docs/db0fa8c8984fc-overview#webhook-payload) already implied that the `event.agent` can have a `null` value because it's demonstrated in the "example webhook payload for a service.updated event is shown below."
This PR makes the Webhook Payload documentation more clear via the following changes:
1. Specifies that the `event.agent` object is specifically a [Resource Reference](https://developer.pagerduty.com/docs/ZG9jOjExMDI5NTYw-resource-references).
2. Explicitly states that the `event.agent` object can have a `null` value.
3. Explicitly states that the `event.client` object can have a `null` value.
It's worth nothing that I have **not** done a comprehensive analysis of whether **other** Webhook `event` fields …
=> Clarify that the v3 Webhook `event.agent` can have a `null`

toc.json
By default, Stoplight creates URL using the page title and with an ugly stable ID prefix (example: https://developer.pagerduty.com/docs/3ec0d67458b0b-obtaining-a-user-o-auth-token-via-code-grant).
They now support customizing each page’s url by adding a "slug" field in the `toc.json` file (see: https://docs.stoplight.io/docs/platform/hosted-docs/stoplight-urls#change-published-urls) .
Using this would: 1) remove the ID prefix 2) automatically re-direct links with the ID to the new ID-less URL 3) allow changing the url to anything, meaning something like the above example could now be https://developer.pagerduty.com/docs/user-oauth-token-via-code-grant. Much cleaner!
Also updates the "try out the api" link to the actual external link (its not a .md article/page, its hosted in …
=> AF-2155 - Update slugs

docs/REST-API/01-Overview.md, docs/webhooks/08-Certificates.md, docs/webhooks/11-Webhook-IPs.md
Updates some wording throughout re: certs and webhooks.
- In `Overview.md`, we actually no longer use DigiCert Global Root CA as our cert's root issuer, it's now DigiCert Global Root G2. In any case, it's better to be more broad and provide a more industry standard recommendation to keep an up-to-date cert store.
- In `Certificates.md`, same as above. Also removes "upcoming certificates" since we have now rotated.
- In `Webhook-IPs.md`, removing some old references to an endpoint from 2022.
=> AF-2038 - webhook cert rotation, update wording

docs/tool-libraries/01-Client-Libraries.md
- Replaces deprecated pdpyras with python-pagerduty - fixes #119 
- Adds PagerDuty Events Client for .NET to the API libraries table - [discussion here](https://community.pagerduty.com/get-involved-16/net-client-library-for-events-api-v2-141)
- Fixes broken link to the Get Involved section in the Community Forums - Jira Ticket AF-2137
- [AF-2137](https://pagerduty.atlassian.net/browse/AF-2137)
[AF-2137]: https://pagerduty.atlassian.net/browse/AF-2137?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
=> AF-2137 - Updates API Client Libraries Page

docs/REST-API/02-Authentication.md
Change to emphasize that account API tokens (keys) are specifically tied to the account and not the user
- Update the `02-Authentication.md` page based on follow-up actions from an incident.
- AUTH-2192
=> Fix wording under Authentication page

docs/webhooks/01-Overview.md
~# DO NOT MERGE until we have confirmation from Product that this change has been communicated to the relevant customers.~
- Adds the `reopened_at` field to the incident event type in the V3 Webhook docs.
STAGING LINK WITH CHANGE: https://developer-v2.pd-staging.com/docs/webhooks-overview#incident
- [INCIDENTS-2666](https://pagerduty.atlassian.net/browse/INCIDENTS-2666)
[INCIDENTS-2666]: https://pagerduty.atlassian.net/browse/INCIDENTS-2666?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
=> [INCIDENTS-2666] Added reopened_at to the V3 Webhooks incident docs.
