docs/REST-API/09-Pagination.md
docs/REST-API/16-Global-Event-Rules-API.md
docs/events-API-v2/01-Overview.md
docs/webhooks/01-v3-Overview.md

Really straightforward, just updating the URLs to match the new format.

Update URLs that pointed to the old format.

---

toc.json

- This was reported as links being mismatched
- [GP-3867.](https://pagerduty.atlassian.net/browse/GP-3867)

Fix links for sample code and developer agreement

---

docs/webhooks/08-Certificates.md

- Corrects the download links for the 2022 webhook intermediate certificates

[DEVI-951] Corrects new intermediate certificates.

---

docs/webhooks/08-Certificates.md

Update dev docs with newest cert info. Moving "new" certificates to "current". Removing "new" section since we won't have new ones for a year.
https://pagerduty.atlassian.net/browse/DEVI-989

Updated 'current' webhooks section, removed 'new' section

---

docs/REST-API/18-PCL-Overview.md
toc.json

Added a description of the PagerDuty Condition Language (PCL).
- ORCA-2575: https://pagerduty.atlassian.net/browse/ORCA-2575

Added docs/REST-API/18-PCL-Overview.md

---

docs/webhooks/04-Signatures.md

- Update Python example
- Add Go example

Cleanup webhook signature examples

---

docs/REST-API/14-Errors.md

Pager Duty returns these error codes which were not in the documentation
- Ref a Jira Ticket if it exists.

Adding missing error codes

---

docs/REST-API/18-PCL-Overview.md

- Documentation update for short-circuiting examples and logic

[ORCA-3381] update documentation with short circuiting

---

docs/webhooks/11-Webhook-IPs.md

Updating date of fixed ip addresses to May 5th.

update date to may 5th

---

docs/webhooks/11-Webhook-IPs.md

- add a json formatted safelist for download
- None

add json format safelist

---

docs/webhooks/03-Mutual-TLS.md

Noticed the formatting for the these steps is broken:
https://developer.pagerduty.com/docs/ZG9jOjExMDI5NTky-mutual-tls#steps-to-verify-pagerdutys-client-certificate
This is just a quick fix for that.
- N/A

Update Mutual TLS formatting

---

docs/REST-API/14-Errors.md

-  Adding Error 2014. This was first [proposed here](https://github.com/PagerDuty/captains-log/pull/46) and is used in [Web](https://github.com/PagerDuty/web/blob/eb5092d3d9ac354ba3af9609586cb72c3e6b7d9a/app/controllers/application_controller.rb#L191) and other PagerDuty services ([example](https://github.com/PagerDuty/message-template-service/blob/cfc0ff9527a44c7056db7b2efa6758296e921d12/apps/api/lib/api/controllers/common_controller_helpers.ex#L12)).
- Ref a Jira Ticket if it exists.

Adding Error 2014

---

docs/app-integration-development/20-OAuth-2-Extended-OAuth.md

- Some initial documentation for using the new Extended OAuth Client
- Staging link: https://developer-v2.pd-staging.com/docs/f5d29537d0007-extended-o-auth

[DEVI-1331] Initial Extended OAuth Docs

---

docs/webhooks/01-Overview.md

Remove V2 webhooks EOL/EOS dates. 
https://pagerduty.atlassian.net/browse/DEVI-1378

DEVI-1378 - Remove V2 webhooks EOL/EOS dates

---

docs/REST-API/18-PCL-Overview.md

- Publish known PCL limits to customers as well as reserved PCL words which have confused customers in the past https://pagerduty.slack.com/archives/CFMEAAR39/p1656515416722509?thread_ts=1656514848.962329&cid=CFMEAAR39
https://pagerduty.atlassian.net/browse/ORCA-3847

ORCA-3847 update PCL docs

---

docs/webhooks/01-Overview.md
docs/webhooks/09-V2-Overview.md

- This updates our developer docs to match the recent changes to EOL plans as already noted in our Support docs.
- [T2D2-136](https://pagerduty.atlassian.net/browse/T2D2-136)
[T2D2-136]: https://pagerduty.atlassian.net/browse/T2D2-136?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

[T2D2-136] Update Webhook EOL Dates

---

docs/webhooks/11-Webhook-IPs.md

- ITS-7323 - Remove us-east-1 IP's from ips list
- [ITS-7323](https://pagerduty.atlassian.net/browse/ITS-7323)
[ITS-7323]: https://pagerduty.atlassian.net/browse/ITS-7323?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

ITS-7323 - Remove us-east-1 IP's from ips list

---

docs/app-integration-development/12-App-OAuth-Token.md

- Scoped OAuth is no longer in Early Access
- [DEVI-1645](https://pagerduty.atlassian.net/browse/DEVI-1645)
[DEVI-1645]: https://pagerduty.atlassian.net/browse/DEVI-1645?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

[DEVI-1645] Hooray API Scopes GA

---

docs/REST-API/19-REST-API-IPs.md

Fix inadvertent word use.

---

docs/REST-API/19-REST-API-IPs.md

Update the REST API IP address page to remove the legacy FELB IPs, and drop the 'new' from the description.
https://pagerduty.atlassian.net/browse/SCL-2149

[SCL-2149] Update REST API IP address list to remove legacy FELB IPs

---

docs/REST-API/01-Overview.md

- adding a blurb about the new procedure to import openapi specs into postman
- [Jira ticket](https://pagerduty.atlassian.net/browse/DEVI-1724)

DEVI-1724 - updating overview with postman procedure

---

docs/webhooks/08-Certificates.md

- The new 2024 mTLS certs are signed by different intermediate and root global CA's. We should publish these as well.
- [DEVI-1821](https://pagerduty.atlassian.net/browse/DEVI-1821)
[DEVI-1821]: https://pagerduty.atlassian.net/browse/DEVI-1821?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

DEVI-1821 - intermediate/root certs for 2024 mTLS

---

docs/webhooks/08-Certificates.md

- Removing last year's certs and changing dates
* [DEVI-1821](https://pagerduty.atlassian.net/browse/DEVI-1821)
[DEVI-1821]: https://pagerduty.atlassian.net/browse/DEVI-1821?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

DEVI-1821 - updated cert documentation

---

docs/REST-API/20-Alert-Grouping-Settings-API.md

- Testing the production developer docs site
- None

Production build test

---

docs/REST-API/20-Alert-Grouping-Settings-API.md

- add back period, and rebuild test
- none

Production rebuild test

---

docs/app-integration-development/02-Developer-Account.md

Details of the change in the [JIRA ticket](https://pagerduty.atlassian.net/browse/AF-1712)

[AF-1712] Remove mention of contacting support team

---

docs/events-API-v2/01-Overview.md

- Add some information about AIOps rate limit increases and how customers and prospective customers can apply for it.
(_I can't figure out how to remove that extra line before the bullet points_)
(_I also added the word 'integration' before key, which isn't pictured_)
https://pagerduty.atlassian.net/browse/ING-2163

[ING-2163] Add AIOps Rate Limit Information

---

.buildkite/stg-pipeline.yml
.github/PULL_REQUEST_TEMPLATE.md
README.md

- Update service ownership to Dev Ecosystem and Public APIs team
- https://pagerduty.atlassian.net/browse/DEVECO-69

DEVECO-69: Update service ownership to Dev Ecosystem and Public APIs team

---

docs/REST-API/02-Authentication.md

Changes the client used in the Python code example (pdpyras is deprecated)
N/A

Use the new python-pagerduty client in the Python code example
